name: SeeBotswana
favicon: null
layout_spectrum: 0.6585654367227107
typography_spectrum: 0.7491164498496801
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7244533763732761
  lightness: 0.8868487735744566
  saturation: 0.939294496551156
  rhythmicContrast: 0.5575443611014634
purpose: []
