name: SeeBotswana
favicon: null
layout_spectrum: 0.25226
typography_spectrum: 0.73631
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9ece5'
    - '#b3c2bf'
    - '#3b3a36'
    - '#6e6e6c'
    - '#7e8683'
  brandStrength: 0
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
