name: SeeBotswana
favicon: null
layout_spectrum: 0.25226
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#abafba'
    - '#fbf2e1'
    - '#211c18'
    - '#736655'
    - '#fee067'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
