name: SeeBotswana
favicon: null
layout_spectrum: 0.25226
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7d4627'
    - '#c9d8c5'
    - '#a8b6bf'
    - '#a88a79'
    - '#f8edd8'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
